ci 5

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -92,16 +92,17 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          echo "Buscando la última ejecución exitosa del CD en main..."
-          RUN_ID=$(gh run list --workflow cd.yml --branch main --status success --limit 1 --json databaseId -q ".[0].databaseId")
+          echo "Loading production manifest..."
+          # Agregamos '2>/dev/null || echo ""' para ignorar el 404 antes de que cd.yml exista en main
+          RUN_ID=$(gh run list --workflow cd.yml --branch main --status success --limit 1 --json databaseId -q ".[0].databaseId" 2>/dev/null || echo "")
           
-          if [ -z "$RUN_ID" ]; then
-            echo "⚠️ No se encontró ninguna ejecución exitosa previa. Saltando descarga."
+          if [ -z "$RUN_ID" ] || [ "$RUN_ID" == "null" ]; then
+            echo "⚠️ Manifest Not found."
           else
-            echo "✅ Descargando artefacto desde el Run ID: $RUN_ID"
-            gh run download $RUN_ID --name dbt-production-manifest --dir dbt_project
-            echo "Verificando archivo descargado:"
-            ls -la dbt_project/manifest.json
+            echo "✅ Downloading ... Run ID: $RUN_ID"
+            gh run download $RUN_ID --name dbt-production-manifest --dir dbt_project || echo "⚠️ Download failed. Pipeline will continue."
+            echo "Checking File:"
+            ls -la dbt_project/manifest.json || true
           fi
 
       - name: Run dbt Slim CI
